# Generated by Django 3.0.8 on 2020-08-21 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'applyings',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('hexcode', models.CharField(default='', max_length=20, null=True)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'image_categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('group', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=2000)),
                ('note', models.CharField(max_length=3000, null=True)),
                ('volume', models.CharField(default='', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('applying', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.Applying')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
                ('color', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.Color')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(default='', max_length=1000)),
                ('image_category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.ImageCategory')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='DetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(default='', max_length=50)),
                ('text2', models.CharField(default='', max_length=50)),
                ('message1', models.CharField(default='', max_length=100)),
                ('message2', models.CharField(default='', max_length=100)),
                ('image_url1', models.URLField(default='', max_length=1000)),
                ('image_url2', models.URLField(default='', max_length=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'db_table': 'detail_info',
            },
        ),
    ]
